// error.vue
<script setup lang="ts">
import type { NuxtError } from "#app";

// prevent reactive update when clearing error
const { error } = defineProps<{
  error: Partial<NuxtError>;
}>();

if (process.dev) console.error(error);

const handleError = async () => clearError({ redirect: "/" });
</script>

<template>
  <div
    w-full
    h-screen
    flex="~ col"
    items-center
    justify-center
    text="center gray-400"
    bg-gray-900
  >
    <h1 text-4xl mb-4>Something went wrong</h1>
    <div text-2xl>
      {{ error.message || "Unknown Error" }}
    </div>
    <button
      @click="handleError"
      mt-12
      font-normal
      text-gray-400
      px-3
      py-2
      rounded-lg
      bg-gray-800
    >
      Go Back
    </button>
  </div>
  <!-- <div text-secondary>
      {{ message }}
    </div>
    <button
      flex
      items-center
      gap-2
      justify-center
      btn-solid
      text-center
      :disabled="state === 'reloading'"
    >
      <span v-if="state === 'reloading'" block animate-spin preserve-3d>
        <span block i-ri:loader-2-fill />
      </span>
      {{ state === "reloading" ? "Reloading" : "Reload" }}
    </button> -->
</template>

// src/app/error.tsx
"use client";

import Link from "next/link";
import { useEffect } from "react";

export default function Error({ error }: { error: Error; reset: () => void }) {
  useEffect(() => {
    console.error(error);
  }, [error]);

  return (
    <div className="w-full h-screen flex items-center justify-center flex-col text-gray-400 text-center">
      <h1 className="text-6xl">
        Houston we have a <span className="text-blue-600">404</span>
      </h1>
      <Link
        href="/"
        passHref
        className="mt-12 font-normal text-gray-400 p-1 px-3 py-2 rounded-lg bg-gray-800">
        Go back
      </Link>
    </div>
  );
}
